from typing import Type

from crewai.tools import BaseTool, tool
from pydantic import BaseModel, Field
from utils.rag_qdrant_hybrid import run_rag_qdrant


@tool("Rag tool qdrant")
def rag_tool_qdrant(question: str) -> str:
    """Answer a question using the Qdrant RAG pipeline.

    Args:
        question (str): Natural language question from the user.

    Returns:
        str: Answer generated by the RAG system.

    Examples:
        >>> rag_tool_qdrant("What is a list in Python?")  # doctest: +SKIP
        'A list is a built-in data structure ...'
    """
    ans_rag = run_rag_qdrant(question)

    return ans_rag


