rag_retriever_task:
  description: >
    Use the rag_tool_qdrant tool to retrieve information relevant to this query: {user_question} and topic: {topic}.
    This tool retrieves the top relevant chunks from a RAG and return them as:
    
    The tool will return chunks from the vector database with their metadata and similarity scores.
    
    Your job is to take the raw results and format each chunk exactly as specified in the expected output.
    
    DO NOT synthesize, summarize, or answer the query directly.
    DO NOT add interpretations or additional text.
    ONLY retrieve and format the document chunks.
  expected_output: >
    A valid JSON array containing the retrieved chunks. Each chunk must be a JSON object with exactly these fields:
    {
      "origin": "RAG",
      "title": "<document title from metadata, or if it's empty the chunk id>",
      "similarity": <similarity score as number>,
      "source": "<chunk _id>",
      "content": "<full retrieved text chunk>",
      "is_trusted": true
    }
    DO NOT ADD ANY ADDITIONAL INFORMATION OR FIELDS BESIDES THE REQUESTED JSON.
    DO NOT ADD "```json" OR ANY OTHER MARKDOWN SYNTAX.
  agent: rag_retriever

web_research_task:
  description: >
    Use the SerperDevTool to find additional relevant information that complements the documents retrieved from rag_retriever_task.
    
    Search query should focus on: {main_topic}, {user_question} and {topic}
    
    Requirements:
    - Conduct 2-3 targeted web searches with different query formulations
    - Select the top 3-5 most authoritative and relevant results
    - Extract meaningful content excerpts (avoid snippets that are too short)
    - Avoid duplicate content: if a web result covers the same information as a RAG result, skip it.
    
    Final step: Merge ALL results from rag_retriever_task with your new web results.
    
  expected_output: >
    A valid JSON array containing:
    1. ALL original elements from rag_retriever_task (with origin="RAG") - 
       copied exactly without modifications
    2. NEW elements from web search (with origin="WEB")
    
    Each web search element must have this structure:
    {
      "origin": "WEB",
      "title": "<webpage title>",
      "similarity": 0.0,
      "source": "<full URL>",
      "content": "<relevant text excerpt, 2-3 paragraphs>",
      "is_trusted": <false>
    }
    DO NOT ADD ANY ADDITIONAL INFORMATION OR FIELDS BESIDES THE REQUESTED JSON.
    DO NOT ADD "```json" OR ANY OTHER MARKDOWN SYNTAX.
  agent: web_researcher
  context: 
    - rag_retriever_task  # ← Usa output del task precedente
  output_file: outputs/rag_crew/final_results_agents.txt

